# Site settings
title:Iman Gareeboo
email: igareeboo@yahoo.com
url: https://imangareeboo.github.io/freelancer-theme_DH/
description: "Website detailing Iman Gareeboo's ongoing projects and research"
keywords: "PhD research, Jane Austen adaptations, Long 18th Century, Revision Theory, Postcolonial Studies"
skills: "Editing - Research - Teaching"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes with the leading hash-tag)
color:
  primary: 18bc9c #88103A
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #EA7FA4
  secondary-dark: 233140 #390719

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:https://www.facebook.com/iman.gareeboo/
  - title: linkedin
    url: www.linkedin.com/in/iman-gareeboo
  - title: instagram
    url: https://www.instagram.com/imangareeboo/
  - title: github
    url: https://github.com/imangareeboo

# Postal address (add as many lines as necessary)
address:
  - line: University of Miami
  - line: 1320 S Dixie Highway, Coral Gables, Miami, FL

# Credits content
credits: 'This site uses the Freelancer theme, a free Jekyll theme, and is produced through GitHub Pages'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
